@host = https://localhost:7244

GET {{host}}/dinners
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlYzE1ODMxMC03ZDQ0LTQzNGQtYTJiNi02N2QyZWQyZjFmMjQiLCJnaXZlbl9uYW1lIjoiQW1pY2hhaSIsImZhbWlseV9uYW1lIjoiTWFudGluYmFuZCIsImp0aSI6ImVjMzkxN2E0LWJjMzAtNGQ0MS1hMjczLTc3N2RiYTY5NDhlZiIsImV4cCI6MTY2MjU4MzA1NSwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.PWwddT0Q2xYz18MwYM2M4PDFuyuS84ryF3d8Gn2uGsw