@host = https://localhost:7244

GET {{host}}/dinners
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0YWNiNTQ1NS0xOGZkLTQ0NjEtYTViZi1jOWE1YWI4NTc3ZDAiLCJnaXZlbl9uYW1lIjoiQW1pY2hhaSIsImZhbWlseV9uYW1lIjoiTWFudGluYmFuZCIsImp0aSI6IjY0ZmVhMjg4LTk1YjItNGIwZC1hNTAxLWRiMDhiMGFmZGUzNyIsImV4cCI6MTY2MjU4MzE4NiwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.jgOMoDhoTFOwIFTA7VvMsDlAHzpbvk2SM5tj1dFBjy8